### ISSUE TITLE
How to use useContext in Class Component

### ISSUE THREAD

**Issue by sw-tt-jethanandnandpal** [deadcoder0904/TranslateRNApp#2]
Hi @deadcoder0904,

Thanks for the nice tutorial. I have one query, how to use useContext in class. I have tried but it gives me hooks error.

Can you please let us know the resolutions to resolved it.

Thanks in advance...!!!

**Comment by deadcoder0904** [comment]
Thank you kind sir. I just Google’d [thissss](https://www.google.com/search?q=use+hooks+in+class+component&rlz=1C5CHFA_enIN752IN752&oq=use+hooks+in+cl&aqs=chrome.0.0j69i57j0l6.3559j0j1&sourceid=chrome&ie=UTF-8)

From the [React docs](https://reactjs.org/docs/hooks-faq.html),

> You can’t use Hooks inside a class component, but you can definitely mix classes and function components with Hooks in a single tree. Whether a component is a class or a function that uses Hooks is an implementation detail of that component.

**Comment by sw-tt-jethanandnandpal** [comment]
I am stuck in one place where I use the useContext. Can you please give some reference about how to do it.

**Comment by deadcoder0904** [comment]
Read the above thing carefully :)
